.PHONY: clean All

All:
	@echo "----------Building project:[ rectangle_class - Debug ]----------"
	@cd "rectangle_class" && "$(MAKE)" -f  "rectangle_class.mk"
clean:
	@echo "----------Cleaning project:[ rectangle_class - Debug ]----------"
	@cd "rectangle_class" && "$(MAKE)" -f  "rectangle_class.mk" clean
