.PHONY: clean All

All:
	@echo "----------Building project:[ replace - Debug ]----------"
	@cd "replaceNew" && "$(MAKE)" -f  "replace.mk"
clean:
	@echo "----------Cleaning project:[ replace - Debug ]----------"
	@cd "replaceNew" && "$(MAKE)" -f  "replace.mk" clean
