.PHONY: clean All

All:
	@echo "----------Building project:[ NewClass - Debug ]----------"
	@cd "NewClass" && "$(MAKE)" -f  "NewClass.mk"
clean:
	@echo "----------Cleaning project:[ NewClass - Debug ]----------"
	@cd "NewClass" && "$(MAKE)" -f  "NewClass.mk" clean
