.PHONY: clean All

All:
	@echo "----------Building project:[ OutputInt - Debug ]----------"
	@cd "OutputInt" && "$(MAKE)" -f  "OutputInt.mk"
clean:
	@echo "----------Cleaning project:[ OutputInt - Debug ]----------"
	@cd "OutputInt" && "$(MAKE)" -f  "OutputInt.mk" clean
